config/routes.rb
Life::Application.routes.draw do
  resources :unit_types

  resources :groceries

  resources :logs
  resources :events

  root :to => 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :category_id, :name, :type_id, :bad, :goal
  has_many :logs
  belongs_to :type
  belongs_to :category

  def running?
    if logs.where("duration IS NULL").count > 0
      true
    else
      false
    end
  end

  def stop
    l = logs.where("duration IS NULL").first
    diff_seconds = (Time.now - l.created_at).round
    diff_minutes = diff_seconds / 60
    l.duration = diff_minutes
    l.save
  end
end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
  attr_accessible :name, :target, :unit_type_id
  belongs_to :unit_type
end

app/models/log.rb
class Log < ActiveRecord::Base
  attr_accessible :event_id, :note, :duration
  belongs_to :event
  self.per_page = 15
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name
  has_many :events
end

app/models/unit_type.rb
class UnitType < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.order("category_id, name")
    if params[:category]
      @events = Event.order("name").where :category_id => params[:category]
    end
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to events_url
    else
      render action => "new"
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to events_url
    else
      render action => "edit"
    end
  end

end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  # GET /groceries
  # GET /groceries.json
  def index
    @groceries = Grocery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groceries }
    end
  end

  # GET /groceries/new
  # GET /groceries/new.json
  def new
    @grocery = Grocery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grocery }
    end
  end

  # GET /groceries/1/edit
  def edit
    @grocery = Grocery.find(params[:id])
  end

  # POST /groceries
  # POST /groceries.json
  def create
    @grocery = Grocery.new(params[:grocery])

    respond_to do |format|
      if @grocery.save
        format.html { redirect_to @grocery, notice: 'Grocery was successfully created.' }
        format.json { render json: @grocery, status: :created, location: @grocery }
      else
        format.html { render action: "new" }
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groceries/1
  # PUT /groceries/1.json
  def update
    @grocery = Grocery.find(params[:id])

    respond_to do |format|
      if @grocery.update_attributes(params[:grocery])
        format.html { redirect_to @grocery, notice: 'Grocery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groceries/1
  # DELETE /groceries/1.json
  def destroy
    @grocery = Grocery.find(params[:id])
    @grocery.destroy

    respond_to do |format|
      format.html { redirect_to groceries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:category]
      @categories = Category.find(params[:category]).events.where(:type_id => "1").order("name")
      @categories_timed = Category.find(params[:category]).events.where(:type_id => "2").order("name")
    elsif params[:event]
      event = Event.find(params[:event])
      if event.type_id == 2 and event.running?
        event.stop
      else
        Log.create(:event_id => params[:event])
      end
      redirect_to root_url
    else
      @categories = Category.order("name")
    end
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def index
    #@logs = Log.order("created_at")
    yesterday = Time.now # - 1.day
    @logs = Log.where(["created_at >= ? AND created_at <= ?", yesterday.beginning_of_day, yesterday.end_of_day]).paginate(:page => params[:page]).order("created_at DESC")
    @logs = Log.paginate(:page => params[:page]).order("created_at DESC")
  end

  def new
    @log = Log.new
  end

  def edit
    @log = Log.find(params[:id])
  end

  def create
    @log = Log.new(params[:log])
    if @log.save
      redirect_to logs_url
    else
      render action => "new"
    end
  end

  def update
    @log = Log.find(params[:id])
    if @log.update_attributes(params[:log])
      redirect_to logs_url
    else
      render action => "edit"
    end
  end

  def destroy
    @log = Log.find(params[:id])
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/unit_types_controller.rb
class UnitTypesController < ApplicationController
  # GET /unit_types
  # GET /unit_types.json
  def index
    @unit_types = UnitType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unit_types }
    end
  end

  # GET /unit_types/1
  # GET /unit_types/1.json
  def show
    @unit_type = UnitType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit_type }
    end
  end

  # GET /unit_types/new
  # GET /unit_types/new.json
  def new
    @unit_type = UnitType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit_type }
    end
  end

  # GET /unit_types/1/edit
  def edit
    @unit_type = UnitType.find(params[:id])
  end

  # POST /unit_types
  # POST /unit_types.json
  def create
    @unit_type = UnitType.new(params[:unit_type])

    respond_to do |format|
      if @unit_type.save
        format.html { redirect_to @unit_type, notice: 'Unit type was successfully created.' }
        format.json { render json: @unit_type, status: :created, location: @unit_type }
      else
        format.html { render action: "new" }
        format.json { render json: @unit_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unit_types/1
  # PUT /unit_types/1.json
  def update
    @unit_type = UnitType.find(params[:id])

    respond_to do |format|
      if @unit_type.update_attributes(params[:unit_type])
        format.html { redirect_to @unit_type, notice: 'Unit type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_types/1
  # DELETE /unit_types/1.json
  def destroy
    @unit_type = UnitType.find(params[:id])
    @unit_type.destroy

    respond_to do |format|
      format.html { redirect_to unit_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/unit_types_helper.rb
module UnitTypesHelper
end

app/views/events/_form.html.erb
<div class="well">
  <%= form_for(@event) do |f| %>
    <div class="field">
      <%= f.label :type_id %>
      <%= f.select "type_id", options_from_collection_for_select(Type.all, "id", "name", @event.type_id) %>
    </div>
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :category_id %>
      <%= f.select "category_id", options_from_collection_for_select(Category.all, "id", "name", @event.category_id) %>
    </div>
    <div class="field">
      <%= f.label :goal %>
      <%= f.number_field :goal %>
    </div>
    <div class="field">
      <%= f.label :bad %>
      <%= f.check_box :bad %>
    </div>
    <div class="actions">
      <%= f.submit nil, :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<ul class="pager">
  <li class="previous">
    <%= link_to 'Back', events_path %>
  </li>
</ul>
<%= render 'form' %>

app/views/events/index.html.erb
<ul class="pager">
  <li class="previous">
    <%= link_to 'New Event', new_event_path %>
  </li>
</ul>
<ul class="nav nav-tabs">
<% Category.all.each do |category| %>
  <li class="<%= 'active' if params[:category] == "#{category.id}" %>"><a href="?category=<%= category.id %>"><%= category.name %></a></li>
<% end %>
</ul>
<table class="table table-striped table-bordered">
  <tr>
    <th class="hidden-phone"></th>
    <th class="hidden-phone">Category</th>
    <th>Name</th>
    <th>Since Last</th>
    <th class="hidden-phone">Goal</th>
    <th>Count</th>
  </tr>
<% @events.each do |event| %>
  <tr>
    <td class="hidden-phone"><%= link_to 'Edit', edit_event_path(event) %></td>
    <td class="hidden-phone"><%= event.category.name %></td>
    <td><%= event.name %></td>
    <td>    
    <% if event.logs.order("created_at").last %>
      <span class="badge"><%= distance_of_time_in_words Time.now, event.logs.order("created_at").last.created_at %></span>
    <% end %>
    </td>
    <td class="hidden-phone"><span class="badge"><%= event.goal %></span></td>
    <td><span class="badge"><%= event.logs.count %></span></td>
  </tr>
<% end %>
</table>

app/views/events/new.html.erb
<ul class="pager">
  <li class="previous">
    <%= link_to 'Back', events_path %>
  </li>
</ul>
<%= render 'form' %>

app/views/groceries/_form.html.erb
<div class="well">
  <%= form_for(@grocery) do |f| %>
    <% if @grocery.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@grocery.errors.count, "error") %> prohibited this grocery from being saved:</h2>

        <ul>
        <% @grocery.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :target %>
      <%= f.text_field :target %>
    </div>
    <div class="field">
      <%= f.label :unit_type_id %>
      <%= f.select "unit_type_id", options_from_collection_for_select(UnitType.all, "id", "name", @grocery.unit_type_id) %>
    </div>
    <div class="actions">
      <%= f.submit nil, :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/groceries/edit.html.erb
<ul class="pager">
  <li class="previous">
    <%= link_to "Back", groceries_path %>
  </li>
</ul>
<%= render 'form' %>

app/views/groceries/index.html.erb
<ul class="pager">
  <li class="previous">
    <%= link_to 'New Grocery', new_grocery_path %>
  </li>
</ul>
<table class="table table-striped table-bordered">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Target</th>
    <th></th>
  </tr>
<% @groceries.each do |grocery| %>
  <tr>
    <td><%= link_to 'Edit', edit_grocery_path(grocery) %></td>
    <td><%= grocery.name %></td>
    <td><%= grocery.target %> <%= grocery.unit_type.name %></td>
    <td><%= link_to 'Destroy', grocery, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/groceries/new.html.erb
<ul class="pager">
  <li class="previous">
    <%= link_to "Back", groceries_path %>
  </li>
</ul>
<%= render 'form' %>

app/views/home/index.html.erb
<br>
<% if params[:category] %>
  <% @categories.each do |event| %>
    <a class="btn btn-primary btn-hero" href="?event=<%= event.id %>"><%= event.name %></a>
  <% end %>
  <br>
  <br>
  <% @categories_timed.each do |event| %>
    <% if event.running? %>
      <a class="btn btn-danger btn-hero" href="?event=<%= event.id %>"><%= event.name %></a>
    <% else %>
      <a class="btn btn-success btn-hero" href="?event=<%= event.id %>"><%= event.name %></a>
    <% end %>
  <% end %>
<% else %>
  <% @categories.each do |category| %>
    <a class="btn btn-hero" href="?category=<%= category.id %>"><%= category.name %></a>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Life</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0;">
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="brand" href="#">Life</a>
        <ul class="nav">
          <li class="<%= 'active' if params[:controller] == 'home' %>"><a href="/">Home</a></li>
          <li class="<%= 'active' if params[:controller] == 'events' %>"><a href="/events">Events</a></li>
          <li class="<%= 'active' if params[:controller] == 'groceries' %>"><a href="/groceries">Groceries</a></li>
          <li class="<%= 'active' if params[:controller] == 'logs' %>"><a href="/logs">Logs</a></li>
        </ul>
      </div>
    </div>
  </div>
  <%= yield %>
</body>
<script>
  $(document).on("click", "a", function(event) {
    event.preventDefault();
    location.href = $(event.target).attr("href");
  });
</script>
</html>

app/views/logs/_form.html.erb
<div class="well">
  <%= form_for(@log) do |f| %>
    <div class="field">
      <%= f.label :event_id %>
      <%= f.select "event_id", options_from_collection_for_select(Event.all, "id", "name", @log.event_id) %>
    </div>
    <div class="field">
      <%= f.label :duration %>
      <%= f.text_field :duration %>
    </div>
    <div class="actions">
      <%= f.submit nil, :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/logs/edit.html.erb
<ul class="pager">
  <li class="previous">
    <%= link_to "Back", logs_path %>
  </li>
</ul>
<%= render 'form' %>

app/views/logs/index.html.erb
<ul class="pager">
  <li class="previous">
    <%= link_to 'New Log', new_log_path %>
  </li>
</ul>
<%= will_paginate @logs %>

<table class="table table-striped table-bordered">
  <tr>
    <th class="hidden-phone"></th>
    <th>Name</th>
    <th>Timestamp</th>
    <th class="hidden-phone">Duration</th>
    <th class="hidden-phone"></th>
  </tr>
  <% @logs.each do |log| %>
  <tr>
    <td class="hidden-phone"><%= link_to 'Edit', edit_log_path(log) %></td>
    <td><%= log.event.name %></td>
    <td><%= log.created_at.localtime.to_s(:short) %></td>
    <td class="hidden-phone"><%= log.duration %></td>
    <td class="hidden-phone"><%= link_to 'Destroy', log, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
  <% end %>
</table>

app/views/logs/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', logs_path, :class => "btn" %>

app/views/unit_types/_form.html.erb
<%= form_for(@unit_type) do |f| %>
  <% if @unit_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit_type.errors.count, "error") %> prohibited this unit_type from being saved:</h2>

      <ul>
      <% @unit_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unit_types/edit.html.erb
<h1>Editing unit_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit_type %> |
<%= link_to 'Back', unit_types_path %>

app/views/unit_types/index.html.erb
<h1>Listing unit_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @unit_types.each do |unit_type| %>
  <tr>
    <td><%= unit_type.name %></td>
    <td><%= link_to 'Show', unit_type %></td>
    <td><%= link_to 'Edit', edit_unit_type_path(unit_type) %></td>
    <td><%= link_to 'Destroy', unit_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Unit type', new_unit_type_path %>

app/views/unit_types/new.html.erb
<h1>New unit_type</h1>

<%= render 'form' %>

<%= link_to 'Back', unit_types_path %>

app/views/unit_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @unit_type.name %>
</p>


<%= link_to 'Edit', edit_unit_type_path(@unit_type) %> |
<%= link_to 'Back', unit_types_path %>